import type { Metadata } from 'next';
import './globals.css';
import 'react-tabs/style/react-tabs.css';
import Header from '@/components/Header';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { headers } from 'next/headers';

export const metadata: Metadata = {
	title: 'Quiz',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const headersList = headers();
	const user = headersList.get('user');

	return (
		<html lang="pt-br">
			<body className={`${user && 'pt-28'}`}>
				{user && <Header user={user} />}

				{children}
				<ToastContainer position="bottom-right" limit={3} />
			</body>
		</html>
	);
}
